export const cardListLoading = [
  {
    _id: 1,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    _id: 2,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    _id: 3,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "Без статуса",
  },
  {
    _id: 4,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Нужно сделать",
  },
  {
    _id: 5,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    _id: 6,
    topic: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    _id: 7,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "В работе",
  },
  {
    _id: 8,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Тестирование",
  },
  {
    _id: 9,
    topic: "Research",
    title: "Название задачи",
    date: "30.10.23",
    status: "Готово",
  },
  {
    _id: 10,
    topic: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    status: "Готово",
  },
];
